### ISSUE TITLE
Allow disabling of right-click menu item

### ISSUE THREAD

**Issue by swrobel** [bvx89/magnetify#1]
I would like to disable the menu entry at the end of this right-click menu:

![screen shot 2014-12-08 at 9 59 00 am](https://cloud.githubusercontent.com/assets/157270/5344097/e0a74026-7ec0-11e4-9d01-a3e2ad36a768.png)

**Comment by bvx89** [comment]
Added option to disable menu item, will upload updated version to chrome web store after everything has been tested.

**Comment by swrobel** [comment]
Thanks!
